In [1]:
import numpy as np
from scipy import linalg

a = np.array([[4, 12, -16],
              [12, 37, -43],
              [-16, -43, 98]])

L = linalg.cholesky(a, lower=True) # 默认计算 upper， 所以指定 lower = True

# array([[ 2.,  0.,  0.],
#       [ 6.,  1.,  0.],
#       [-8.,  5.,  3.]])

np.allclose(np.dot(L, L.T) , a) # 验证计算

True

In [4]:
L

array([[ 2.,  0.,  0.],
       [ 6.,  1.,  0.],
       [-8.,  5.,  3.]])

In [2]:
L @ L.T

array([[  4.,  12., -16.],
       [ 12.,  37., -43.],
       [-16., -43.,  98.]])

In [17]:
import scipy

a = np.array([[4, 12, -16],
              [12, 37, -43],
              [-16, -43, 98]])


chol_factor, lower = scipy.linalg.cho_factor(a, lower=True, check_finite=False)

In [18]:
chol_factor

array([[  2.,  12., -16.],
       [  6.,   1., -43.],
       [ -8.,   5.,   3.]])

In [9]:
lower

True

In [2]:
import numpy as np
a = np.array([1, 2, 3])

a @ a.T

14

In [5]:
import scipy.linalg
import numpy as np
cov = np.array([
    [3, 1],
    [1, 0.5]
])

L = np.linalg.cholesky(cov)  # 分解为 cov = LL^T
d = np.array([[1, 2]])
z = scipy.linalg.solve_triangular(
    L, d.T, lower=True, check_finite=False,
    overwrite_b=True)
np.sum(z * z, axis=0)

array([17.])

In [8]:
z

array([[0.57735027],
       [4.0824829 ]])

In [7]:
np.sum(z.T @ z)

17.000000000000007

In [1]:
import numpy as np

In [7]:
a = np.array(
    [[1, 2, 3],
    [2, 3, 4]]
)

b = np.array(
    [[1, 2, 3],
    [6, 3, 4],
    [8, 4, 5],
    [1, 5, 6]]
)

In [9]:
b.min(axis=0)

array([1, 2, 3])

In [3]:
f = []
f += [1, 2, 3]

In [5]:
f += [2,3,4]

In [6]:
f

[1, 2, 3, 2, 3, 4]

In [7]:
a = {}

In [8]:
a.setdefault(1, []).append([1, 2, 3])

In [10]:
a[1].append([2, 3, 4])

In [11]:
a

{1: [[1, 2, 3], [2, 3, 4]]}

In [1]:
import numpy as np


a = np.asarray(None)

In [4]:
a == None

True

[array(None, dtype=object),
 array(None, dtype=object),
 array(None, dtype=object)]